---
title: "BLISS breakpoints - Import of raw data"
author: "Hilmar Berger"
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: false
    number_sections: true
    code_folding: hide
    
pdf_document:
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---

```{r, message=FALSE}
library(data.table)
library(GenomicRanges)
```

This script will import DSB break sites from files produced by the BLISS pipeline. We will filter out difficult genomic regions and adjust the breakpoints to represent 

```{r}
input_folders = c("../../Data/Breaks_raw")

all_files_list = list()
for (dd in input_folders) {
  all_files_list[[dd]] = list.files(path=dd, pattern="*.tsv", recursive = T, full.names = T)  
}

standard_chroms = genomeStyles()[["Homo_sapiens"]]$NCBI
standard_chroms = standard_chroms[!standard_chroms == "MT"]

all_tabs = list()
for (ff in unlist(all_files_list)) {
  sample_name = unlist(strsplit(basename(ff), "__"))[1]
  tmp = fread(paste0("gzip -dc ",ff), sep="\t")
  tmp$V1 = gsub("chrM","MT", gsub("chr","", tmp$V1))
  tmp$sample = sample_name
  all_tabs[[sample_name]] = subset(tmp, V1 %in% standard_chroms)
}
  
all_tabs_combined = do.call(rbind, all_tabs)
setnames(all_tabs_combined, colnames(all_tabs_combined), c("chrom","start","end","strand","UMI", "read_count", "sample"))

setorder(all_tabs_combined, "sample","chrom","start")

```

```{r, fig.height=6, fig.width=10}
tmp = all_tabs_combined[, .(count=.N), by=c("sample")] 
par(mar=c(15,6,4,1))
barplot(tmp$count, names.arg=tmp$sample, las=2, main="Break-end counts per sample", ylab="Count")
```



```{r, message=FALSE}
###################################################################
####                        difficult sites                    ####
###################################################################

# load High_coverage regions (5pct - top 5% of the most 'covered' regions; 1pct - top 1% of the most 'covered' regions)
load("../../Data/External/UCSC/HighCov_ranges.Rdata")

# load Low_mappability regions
load("../../Data/External/UCSC/low_mappability_100mer_h19.Rdata")

# blacklist (convert bed file to GRanges object)
blcklst <- fread("../../Data/External/UCSC/hg19_DAC_blacklist.bed")
names<-c("chr","start","end")
colnames(blcklst) <- names
blcklst_GRanges <- GRanges(as.character(blcklst$chr), IRanges(start=blcklst$start, end=blcklst$end))
suppressMessages(seqlevelsStyle(blcklst_GRanges) <- 'NCBI')

dif_list = list()
dif_list[[1]] <- HighCov_site_ranges_5pct
dif_list[[2]] <- low_mappability_regions
dif_list[[3]] <- blcklst_GRanges

# Merge all GRanges into 1 object
dif <- do.call("c", dif_list)
dif_sort <- dif
```

```{r}
# We here assume that the coordinates in the TSV files are in BED notation (0-based coordinates, end is not included)
# DSB positions for reads on + strand are generated by the BLISS pipeline as the first in the genomic fragment
# DSB positions for reads on - strand are generated by the BLISS pipeline as the last before the genomic fragment (i.e. outside the fragment)
# We change the start/end for the + strand so that is also outside the genomic fragment (note that all_tabs_combined has still coordinates in BED style)
break_ranges = with(all_tabs_combined, GRanges(chrom, IRanges(ifelse(strand=="+", start, start+1), ifelse(strand=="+", end-1, end)), strand = strand, umi=UMI, read_count = read_count, index=1:nrow(all_tabs_combined), sampleID=sample))

ovlp = findOverlaps(break_ranges, dif_sort, ignore.strand=T)

break_ranges_excluded_difficult_regions = break_ranges[-break_ranges[queryHits(ovlp)]$index]
```

```{r}
tmp = strsplit(gsub("-", "_",names(all_tabs)), "_")

ed = data.frame(sampleID = names(all_tabs), 
                library=unlist(sapply(tmp, `[`,1)),
                cells=unlist(sapply(tmp, `[`,2)),
                condition=unlist(sapply(tmp, `[`,3)),
                library_sub_sampleID = unlist(sapply(tmp, `[`,4)),
                barcode = unlist(sapply(tmp, `[`,5)),
                stringsAsFactors = F
              )
ed$replicate_ID = with(ed, paste0(library,"_", library_sub_sampleID))
rownames(ed) = ed$sampleID
ed$technical_replicate=ifelse(grepl("b$",ed$library), TRUE, FALSE)
              
```

```{r}
suppressMessages(seqlevelsStyle(break_ranges_excluded_difficult_regions) <- "NCBI")
ed = read.table("../../Data/ExpDesign_fixed.txt", sep="\t", header=T, stringsAsFactors = F)

r_strand = as.character(strand(break_ranges_excluded_difficult_regions))
r_start = as.integer(start(break_ranges_excluded_difficult_regions))
r_end = as.integer(end(break_ranges_excluded_difficult_regions))
# breakpoint positions as reported by BLISS (and adjusted) are always the last position before the observed genomic fragment as seen from the linker.
# Here we export intervals of 2bp that contain the breakpoint between them
# On + strand reads, the DSB is between the DSB position and the next base. 
# On - strand the DSB is between the preceding base and the DSB position
# BED files requires conversion of the start positions to a 0-based scaled (from the 1-based scale used in R)
breaks_all_dt = data.table(chr=as.character(seqnames(break_ranges_excluded_difficult_regions)), start=ifelse(r_strand=="+", r_start-1L, r_start-2L), end=ifelse(r_strand=="+", r_start+1L, r_start), umi=break_ranges_excluded_difficult_regions$umi, score=rep(0L, length(r_strand)), strand=r_strand, sampleID=break_ranges_excluded_difficult_regions$sampleID)

breaks_agg = breaks_all_dt[, .(count = .N, umis=list(umi), score=0L), by=c("chr","start","end","strand", "sampleID")]

breaks_agg[breaks_agg$count == 1, umis_str:=paste0("1:",unlist(umis)),by=c("chr","start","end","strand", "sampleID")]
breaks_agg[breaks_agg$count > 1, umis_str:=paste0(count, ":", paste(unique(sort(unlist(umis))), collapse=",")), by=c("chr","start","end","strand", "sampleID")]

included_samples = ed$sampleID
sel_cols = c("chr","start","end","umis_str", "score", "strand")
for (s in included_samples) {
  fwrite(breaks_agg[breaks_agg$sampleID==s, sel_cols, with=F], col.names = F, file=file.path("../../Data/DSB_positions_processed", paste0(s,".bed")), quote = F, sep="\t" )
}

fwrite(breaks_agg, file="../../Data/Breaks_filtered/breaks_agg.txt", sep="\t")
```

```{r, fig.width=10}
par(mar=c(15,4,4,1))
tmp = breaks_agg[, .(count=.N), by="sampleID"]
barplot(tmp$count, names.arg = tmp$sampleID, las=2, ylab="Count", main="DSB counts after filtering and collapsing unique sites")
```

# Software versions

```{r}
sessionInfo()
```

