---
title: "BLISS breakpoints from cell line with integrated AsiSI in induced/uninduced condition"
output: html_document
---

```{r, message=FALSE}
library(data.table)
library(GenomicRanges)
```


```{r}
all_files_list=list("Uninduced"="../../../Data/External/BLISS_AsiSI/SRR5441981/BED/AsiSI_uninduced_positions.bed.gz","Induced"="../../../Data/External/BLISS_AsiSI/SRR5441980/BED/AsiSI_induced_positions.bed.gz")

standard_chroms = genomeStyles()[["Homo_sapiens"]]$NCBI
standard_chroms = standard_chroms[!standard_chroms == "MT"]

all_tabs = list()
for (ff in unlist(all_files_list)) {
  sample_name = unlist(strsplit(basename(ff), "__"))[1]
  tmp = fread(cmd=paste0("zcat ",ff), sep="\t")
  tmp$sample = sample_name
  # keep only reads with mapping length at least 40bp and >= 30 mapping quality
  setnames(tmp, colnames(tmp), c("chrom","start","end","readID","MAPQ","strand","sample"))
  tmp = subset(tmp, chrom %in% standard_chroms & MAPQ>=30 & (end-start) > 40)

  tmp_agg = tmp[, .(count=.N), by=c("chrom","start","end","strand","sample")]
  all_tabs[[sample_name]] = tmp_agg
}
  
all_tabs_combined = do.call(rbind, all_tabs)

setorder(all_tabs_combined, "sample","chrom","start")

```

```{r, fig.height=6, fig.width=10}
tmp = all_tabs_combined[, .(count=.N), by=c("sample")] 
par(mar=c(15,6,4,1))
barplot(tmp$count, names.arg=tmp$sample, las=2, main="Unique break-end site counts per sample")
```


```{r, message=FALSE}
###################################################################
####                        difficult sites                    ####
###################################################################

# load High_coverage regions (5pct - top 5% of the most 'covered' regions; 1pct - top 1% of the most 'covered' regions)
load("../../../Data/External/UCSC/HighCov_ranges.Rdata")

# load Low_mappability regions
load("../../../Data/External/UCSC/low_mappability_100mer_h19.Rdata")

# blacklist (convert bed file to GRanges object)
blcklst <- fread("../../../Data/External/UCSC/hg19_DAC_blacklist.bed")
names<-c("chr","start","end")
colnames(blcklst) <- names
blcklst_GRanges <- GRanges(as.character(blcklst$chr), IRanges(start=blcklst$start, end=blcklst$end))
suppressMessages(seqlevelsStyle(blcklst_GRanges) <- 'NCBI')

dif_list = list()
dif_list[[1]] <- HighCov_site_ranges_5pct
dif_list[[2]] <- low_mappability_regions
dif_list[[3]] <- blcklst_GRanges

# Merge all GRanges into 1 object
dif <- do.call("c", dif_list)
dif_sort <- dif
```

```{r}
# We here assume that the coordinates in the TSV files are in BED notation (0-based coordinates, end is not included)
# DSB positions for reads on + strand are generated by bamToBED as the first in the genomic fragment
# DSB positions for reads on - strand are generated by bamToBED pipeline as the last within the genomic fragment (i.e. outside the fragment)
# We change the start/end for both strands so that is also outside the genomic fragment (note that all_tabs_combined has still coordinates in BED style)
break_ranges = with(all_tabs_combined, GRanges(chrom, IRanges(ifelse(strand=="+", start, end+1), ifelse(strand=="+", start, end+1)), strand = strand, read_count = count, index=1:nrow(all_tabs_combined), sampleID=sample))

ovlp = findOverlaps(break_ranges, dif_sort, ignore.strand=T)

break_ranges_excluded_difficult_regions = break_ranges[-break_ranges[queryHits(ovlp)]$index]

```

```{r}
tmp = strsplit(gsub("-", "_",gsub(".bed","",names(all_tabs))), "_")

ed = data.frame(sampleID = names(all_tabs), 
                library=unlist(sapply(tmp, function(x) paste(x[1:2],collapse="_"))),
                cells=rep("DiVa"),
                condition = unlist(sapply(tmp, `[`,2)),
                library_sub_sampleID = rep("1",2),
                barcode = rep("CATCACGC",2),
                stringsAsFactors = F
              )
ed$replicate_ID = with(ed, paste0(library,"_", library_sub_sampleID))
rownames(ed) = ed$sampleID
ed$technical_replicate=ifelse(grepl("b$",ed$library), TRUE, FALSE)
                
```


```{r}
save(break_ranges_excluded_difficult_regions, ed, file="../../../Data/BLISS_AsiSI/Filtered_break_end_sites.Rdata" )
```


